# Generated by Django 4.0.1 on 2022-06-02 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
