# Generated by Django 4.0.1 on 2022-06-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
